# Generated by Django 4.1.7 on 2023-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_auto_20230305_1854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
