"""Глобальные константы приложения posts"""

POST_PREVIEW_SYMBOLS: int = 15
COMMENT_PREVIEW_SYMBOLS: int = 15

CACHE_TIMEOUT_SECONDS: int = 5

POSTS_PER_PAGE: int = 10

TESTS_POSTS_PER_PAGE_MULTIPLIER: float = 1.2

TESTS_ALL_POSTS_TOTAL_PAGES: int = 4
TESTS_USER_POSTS_TOTAL_PAGES: int = 3
TESTS_GROUP_POSTS_TOTAL_PAGES: int = 2
TESTS_OTHER_USER_POSTS_TOTAL_PAGES: int = 2
TESTS_OTHER_GROUP_POSTS_TOTAL_PAGES: int = 3
